/* Build viewer/papers.html with the shelf already in it.
 *
 *   viewer/papers.template.html  +  render() from viewer/home.js  ->  viewer/papers.html
 *
 * The library page is the same for every visitor and only changes when the
 * pipeline runs, so there is no reason to ship it as thirty paper bundles and
 * assemble it in the browser. It used to: papers.html document.write'd one
 * <script> per registered paper, 3.4MB over the wire and 15MB parsed, all of it
 * parser-blocking, to draw a list of cards that reads about 1% of that data.
 *
 * The markup is not rewritten here. This runs the viewer's own render() under a
 * DOM stub small enough that home.js does not know it is not in a browser, so
 * the cards stay defined in one place and cannot drift from what the reader
 * would have drawn. home.js keeps render() and skips it when the cards are
 * already on the page.
 *
 * Run after pipeline/bundle.py, which writes the register and bundles this
 * reads. Output is committed like the bundles are.
 */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const p = (...xs) => path.join(ROOT, ...xs);
const read = (f) => fs.readFileSync(f, "utf8");

/* ---------- a DOM only as wide as home.js reaches ---------- */

/* render() writes one string into #home and hands it to three wiring passes.
 * The passes look for things this page does not have yet - tab groups, the
 * request form, KaTeX - so each one finds nothing and returns. That is the
 * whole surface: an element that records what was assigned to it, a lookup
 * that answers for #home and nothing else, and a load event to fire. */
function stubDom() {
  const home = {
    innerHTML: "",
    firstElementChild: null,       // empty, so home.js renders rather than wires
    querySelectorAll: () => [],    // no tab groups and no ask buttons to bind
  };
  let onReady = null;
  const document = {
    getElementById: (id) => (id === "home" ? home : null),
    addEventListener: (type, cb) => { if (type === "DOMContentLoaded") onReady = cb; },
    querySelectorAll: () => [],
  };
  return { home, document, fire: () => { if (onReady) onReady(); } };
}

function renderShelf() {
  const { home, document, fire } = stubDom();

  const sandbox = { document, console, SkimTheme: { mount() {} } };
  sandbox.window = sandbox;          // so `window.X = 1` also defines a bare global X
  sandbox.globalThis = sandbox;
  vm.createContext(sandbox);

  const run = (file) => new vm.Script(read(file), { filename: file }).runInContext(sandbox);

  run(p("register.js"));
  const ids = Object.keys(sandbox.window.SKIM_REGISTER?.papers ?? {});
  for (const id of ids) {
    const bundle = p("papers", id, "data", "js", "bundle.js");
    if (fs.existsSync(bundle)) run(bundle);
    else console.warn(`  ! no bundle for ${id} - it will be left off the shelf`);
  }

  run(p("viewer", "home.js"));
  fire();

  if (!home.innerHTML) throw new Error("render() wrote nothing into #home");
  return { html: home.innerHTML, papers: ids.length };
}

/* ---------- the page ---------- */

/* Concept names carry the paper's own notation, which is sometimes inline
 * math. Usually it is not: as written, no card on the shelf holds a single
 * dollar span. So the typesetter is linked only when there is something for it
 * to set, and a paper that arrives with math in a name brings it back without
 * anyone having to remember to. */
const KATEX = [
  '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css">',
  '<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"><\/script>',
  '<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/contrib/auto-render.min.js"><\/script>',
].join("\n");

function main() {
  const { html, papers } = renderShelf();
  const hasMath = /\$[^$\n]{1,200}\$/.test(html);

  const template = read(p("viewer", "papers.template.html"));
  for (const mark of ["<!--CARDS-->", "<!--MATH-->"]) {
    if (!template.includes(mark)) throw new Error(`papers.template.html has no ${mark}`);
  }

  const banner = "<!-- Generated by pipeline/prerender.mjs from papers.template.html.\n" +
    "     Do not edit: the next pipeline run overwrites it. The shell is in\n" +
    "     viewer/papers.template.html, the cards in render() in viewer/home.js. -->\n";

  const out = banner + template
    .replace("<!--MATH-->", hasMath ? KATEX : "<!-- no inline math on the shelf; KaTeX not loaded -->")
    .replace("<!--CARDS-->", () => html);

  const dest = p("viewer", "papers.html");
  fs.writeFileSync(dest, out, "utf8");

  const kb = (n) => (n / 1024).toFixed(0) + "KB";
  console.log(`prerendered viewer/papers.html: ${papers} papers, ${kb(out.length)}` +
    (hasMath ? ", KaTeX linked" : ", no math"));
}

main();
